/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesES;

/**
 *
 * @author Mi PC
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(bc, "src/images/bc.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        aTitle = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        logoBlack = new javax.swing.JLabel();
        aTitle1 = new javax.swing.JLabel();
        bTitle = new javax.swing.JLabel();
        ienvenidoTitle = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        signupBtn = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        skillbridgeName = new javax.swing.JLabel();
        greenBoard = new javax.swing.JLabel();
        whiteBoard = new javax.swing.JLabel();
        bc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lockIcon.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 30, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/idIcon.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 30, 30));

        aTitle.setFont(new java.awt.Font("Questrial", 0, 51)); // NOI18N
        aTitle.setForeground(new java.awt.Color(0, 0, 0));
        aTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aTitle.setText("a");
        getContentPane().add(aTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 40, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackMarker.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 256, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starSmall.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 64, 63));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/starBig.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 141, 138));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/woman.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 398, 337));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 256, 308));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenShadow2.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 271, 110));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenShadow.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 158, 64));

        jLabel6.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 584, 60, -1));

        jLabel5.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Acceder");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 524, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenBtn.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 570, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenBtn.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 210, 40));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 450, 210, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("Password");
        jPasswordField1.setBorder(null);
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 428, 180, -1));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 210, 10));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("ID");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 338, 180, -1));

        logoBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoBlack.png"))); // NOI18N
        getContentPane().add(logoBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 120, 80));

        aTitle1.setFont(new java.awt.Font("Questrial", 1, 66)); // NOI18N
        aTitle1.setForeground(new java.awt.Color(0, 0, 0));
        aTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aTitle1.setText("Skillbridge");
        getContentPane().add(aTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 330, -1));

        bTitle.setFont(new java.awt.Font("Questrial", 0, 66)); // NOI18N
        bTitle.setForeground(new java.awt.Color(255, 255, 255));
        bTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bTitle.setText("B");
        getContentPane().add(bTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 120, -1, 90));

        ienvenidoTitle.setFont(new java.awt.Font("Questrial", 0, 66)); // NOI18N
        ienvenidoTitle.setForeground(new java.awt.Color(0, 0, 0));
        ienvenidoTitle.setText("ienvenido");
        getContentPane().add(ienvenidoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 290, 90));

        loginBtn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        signupBtn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Sign Up");
        getContentPane().add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, 30));

        skillbridgeName.setFont(new java.awt.Font("Questrial", 0, 36)); // NOI18N
        skillbridgeName.setForeground(new java.awt.Color(255, 255, 255));
        skillbridgeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skillbridgeName.setText("SkillBridge");
        getContentPane().add(skillbridgeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 50));

        greenBoard.setBackground(new java.awt.Color(255, 255, 255));
        greenBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenBoard.png"))); // NOI18N
        getContentPane().add(greenBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1210, 710));

        whiteBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteBoard.png"))); // NOI18N
        getContentPane().add(whiteBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1290, 710));

        bc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bc.png"))); // NOI18N
        getContentPane().add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 1290, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aTitle;
    private javax.swing.JLabel aTitle1;
    private javax.swing.JLabel bTitle;
    private javax.swing.JLabel bc;
    private javax.swing.JLabel greenBoard;
    private javax.swing.JLabel ienvenidoTitle;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoBlack;
    private javax.swing.JLabel signupBtn;
    private javax.swing.JLabel skillbridgeName;
    private javax.swing.JLabel whiteBoard;
    // End of variables declaration//GEN-END:variables
}
