/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesES;

/**
 *
 * @author Mi PC
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public signup() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(bc, "src/images/bc.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        aTitle = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        logoBlack = new javax.swing.JLabel();
        aTitle1 = new javax.swing.JLabel();
        ienvenidoTitle = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        signupBtn = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        skillbridgeName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        whiteBoard = new javax.swing.JLabel();
        bc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star3.png"))); // NOI18N
        jLabel20.setText("jLabel20");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 57, 56));

        jLabel6.setFont(new java.awt.Font("Questrial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 570, 60, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenBtn.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 210, 40));

        jTextField6.setBackground(new java.awt.Color(247, 247, 247));
        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 270, 33));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/arrow.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 96, 60));

        jLabel10.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Contraseña");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/phrase.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 460, 210, 86));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hat2.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 123, 195));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hat1.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 218, 344));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/w1.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 124, 125, 150));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/w2.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 134, 120, 139));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/manGrad.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 330, 309, 380));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/star2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 380, 100, 100));

        jTextField7.setBackground(new java.awt.Color(247, 247, 247));
        jTextField7.setForeground(new java.awt.Color(102, 102, 102));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 270, 33));

        jLabel11.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Repetir contraseña");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, 20));

        jTextField5.setBackground(new java.awt.Color(247, 247, 247));
        jTextField5.setForeground(new java.awt.Color(102, 102, 102));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 210, 33));

        jLabel9.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Celular");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        jTextField4.setBackground(new java.awt.Color(247, 247, 247));
        jTextField4.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 210, 33));

        jLabel8.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("ID Estudiantil");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        jTextField3.setBackground(new java.awt.Color(247, 247, 247));
        jTextField3.setForeground(new java.awt.Color(102, 102, 102));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 780, 33));

        jLabel7.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jTextField2.setBackground(new java.awt.Color(247, 247, 247));
        jTextField2.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 310, 33));

        jLabel3.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Apellidos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 70, -1));

        jTextField1.setBackground(new java.awt.Color(247, 247, 247));
        jTextField1.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 330, 33));

        jLabel2.setFont(new java.awt.Font("Questrial", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombres");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, -1));

        aTitle.setFont(new java.awt.Font("Questrial", 0, 51)); // NOI18N
        aTitle.setForeground(new java.awt.Color(255, 255, 255));
        aTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aTitle.setText("a");
        getContentPane().add(aTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 40, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blackMarker.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 256, -1, -1));

        logoBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteLogo.png"))); // NOI18N
        getContentPane().add(logoBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 120, 80));

        aTitle1.setFont(new java.awt.Font("Questrial", 1, 66)); // NOI18N
        aTitle1.setForeground(new java.awt.Color(255, 255, 255));
        aTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aTitle1.setText("Skillbridge");
        getContentPane().add(aTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 330, -1));

        ienvenidoTitle.setFont(new java.awt.Font("Questrial", 0, 66)); // NOI18N
        ienvenidoTitle.setForeground(new java.awt.Color(255, 255, 255));
        ienvenidoTitle.setText("Bienvenido");
        getContentPane().add(ienvenidoTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 340, 90));

        loginBtn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        signupBtn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Sign Up");
        getContentPane().add(signupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 90, 30));

        skillbridgeName.setFont(new java.awt.Font("Questrial", 0, 36)); // NOI18N
        skillbridgeName.setForeground(new java.awt.Color(255, 255, 255));
        skillbridgeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skillbridgeName.setText("SkillBridge");
        getContentPane().add(skillbridgeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/greenLargeBoard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 60, 1116, 214));

        whiteBoard.setBackground(new java.awt.Color(204, 204, 204));
        whiteBoard.setForeground(new java.awt.Color(102, 102, 102));
        whiteBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteBoard.png"))); // NOI18N
        getContentPane().add(whiteBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1290, 710));

        bc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bc.png"))); // NOI18N
        getContentPane().add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 1290, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aTitle;
    private javax.swing.JLabel aTitle1;
    private javax.swing.JLabel bc;
    private javax.swing.JLabel ienvenidoTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoBlack;
    private javax.swing.JLabel signupBtn;
    private javax.swing.JLabel skillbridgeName;
    private javax.swing.JLabel whiteBoard;
    // End of variables declaration//GEN-END:variables
}
