/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Materia;

import java.awt.Color;

/**
 *
 * @author Mi PC
 */
public class actividad extends javax.swing.JPanel {

    /**
     * Creates new form actividad
     */
    public actividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        actPanel = new javax.swing.JPanel();
        deleteactBtn = new javax.swing.JPanel();
        deleteactTxt = new javax.swing.JLabel();
        actName = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actPanel.setBackground(new java.awt.Color(15, 96, 99));
        actPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteactBtn.setBackground(new java.awt.Color(223, 91, 91));

        deleteactTxt.setFont(new java.awt.Font("Questrial", 0, 17)); // NOI18N
        deleteactTxt.setForeground(new java.awt.Color(255, 255, 255));
        deleteactTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteactTxt.setText("x");
        deleteactTxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteactTxtMouseMoved(evt);
            }
        });
        deleteactTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteactTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout deleteactBtnLayout = new javax.swing.GroupLayout(deleteactBtn);
        deleteactBtn.setLayout(deleteactBtnLayout);
        deleteactBtnLayout.setHorizontalGroup(
            deleteactBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteactBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deleteactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        deleteactBtnLayout.setVerticalGroup(
            deleteactBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteactBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deleteactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        actPanel.add(deleteactBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        background.add(actPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 100));

        actName.setFont(new java.awt.Font("Questrial", 0, 17)); // NOI18N
        actName.setForeground(new java.awt.Color(0, 0, 0));
        actName.setText("Actividad");
        background.add(actName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteactTxtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteactTxtMouseMoved
        deleteactBtn.setBackground(new Color(191,40,40));
    }//GEN-LAST:event_deleteactTxtMouseMoved

    private void deleteactTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteactTxtMouseExited
         deleteactBtn.setBackground(new Color(223,91,91));
    }//GEN-LAST:event_deleteactTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actName;
    private javax.swing.JPanel actPanel;
    private javax.swing.JPanel background;
    private javax.swing.JPanel deleteactBtn;
    private javax.swing.JLabel deleteactTxt;
    // End of variables declaration//GEN-END:variables
}
