/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Materia;

/**
 *
 * @author Mi PC
 */
public class panelAsig extends javax.swing.JPanel {

    /**
     * Creates new form panelAsig
     */
    public panelAsig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        backBtn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        asigName = new javax.swing.JLabel();
        videosSection = new javax.swing.JPanel();
        videosTitle = new javax.swing.JLabel();
        loadBtn = new javax.swing.JPanel();
        loadIcon = new javax.swing.JLabel();
        videos = new javax.swing.JPanel();
        actsSection = new javax.swing.JPanel();
        actsTitle = new javax.swing.JLabel();
        loadBtn1 = new javax.swing.JPanel();
        loadIcon1 = new javax.swing.JLabel();
        acts = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Retroceder");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backIcon.png"))); // NOI18N

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel22)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        asigName.setFont(new java.awt.Font("Questrial", 0, 26)); // NOI18N
        asigName.setForeground(new java.awt.Color(221, 224, 229));
        asigName.setText("// Asignatura");
        background.add(asigName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        videosSection.setBackground(new java.awt.Color(204, 204, 204));

        videosTitle.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        videosTitle.setForeground(new java.awt.Color(0, 0, 0));
        videosTitle.setText("Actividades");

        loadBtn.setBackground(new java.awt.Color(64, 174, 178));

        loadIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loadIcon.png"))); // NOI18N

        javax.swing.GroupLayout loadBtnLayout = new javax.swing.GroupLayout(loadBtn);
        loadBtn.setLayout(loadBtnLayout);
        loadBtnLayout.setHorizontalGroup(
            loadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadBtnLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(loadIcon)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        loadBtnLayout.setVerticalGroup(
            loadBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadBtnLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(loadIcon)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        videos.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout videosLayout = new javax.swing.GroupLayout(videos);
        videos.setLayout(videosLayout);
        videosLayout.setHorizontalGroup(
            videosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        videosLayout.setVerticalGroup(
            videosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout videosSectionLayout = new javax.swing.GroupLayout(videosSection);
        videosSection.setLayout(videosSectionLayout);
        videosSectionLayout.setHorizontalGroup(
            videosSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videosSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videosSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(videosTitle)
                    .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(videos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        videosSectionLayout.setVerticalGroup(
            videosSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videosSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(videosTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(videos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(videosSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 950, 150));

        actsSection.setBackground(new java.awt.Color(204, 204, 204));

        actsTitle.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        actsTitle.setForeground(new java.awt.Color(0, 0, 0));
        actsTitle.setText("Videos");

        loadBtn1.setBackground(new java.awt.Color(64, 174, 178));

        loadIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loadIcon.png"))); // NOI18N

        javax.swing.GroupLayout loadBtn1Layout = new javax.swing.GroupLayout(loadBtn1);
        loadBtn1.setLayout(loadBtn1Layout);
        loadBtn1Layout.setHorizontalGroup(
            loadBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadBtn1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(loadIcon1)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        loadBtn1Layout.setVerticalGroup(
            loadBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadBtn1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(loadIcon1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        acts.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout actsLayout = new javax.swing.GroupLayout(acts);
        acts.setLayout(actsLayout);
        actsLayout.setHorizontalGroup(
            actsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        actsLayout.setVerticalGroup(
            actsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout actsSectionLayout = new javax.swing.GroupLayout(actsSection);
        actsSection.setLayout(actsSectionLayout);
        actsSectionLayout.setHorizontalGroup(
            actsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actsSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actsTitle)
                    .addComponent(loadBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(acts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actsSectionLayout.setVerticalGroup(
            actsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actsSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(acts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        background.add(actsSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 950, 150));

        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        if (ventanaAnterior != null) {

            // 1. Verificamos si la ventana anterior implementa la interfaz Actualizable.
            if (ventanaAnterior instanceof Actualizable) {

                // 2. Si lo hace, hacemos el casting a la interfaz y llamamos al método.
                ((Actualizable) ventanaAnterior).actualizarNombreEnUI();

                System.out.println("✅ Ventana Anterior notificada para recargar el nombre.");
            }

            // 3. Hacemos visible la ventana anterior (ya actualizada).
            ventanaAnterior.setVisible(true);
        }

        // 4. Cerrar la ventana de perfil (solo una vez).
        this.dispose();
        // ⬅️ Fin del método backBtnMouseClicked.

    }//GEN-LAST:event_backBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acts;
    private javax.swing.JPanel actsSection;
    private javax.swing.JLabel actsTitle;
    private javax.swing.JLabel asigName;
    private javax.swing.JPanel backBtn;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel loadBtn;
    private javax.swing.JPanel loadBtn1;
    private javax.swing.JLabel loadIcon;
    private javax.swing.JLabel loadIcon1;
    private javax.swing.JPanel videos;
    private javax.swing.JPanel videosSection;
    private javax.swing.JLabel videosTitle;
    // End of variables declaration//GEN-END:variables
}
