/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Materia;

import java.awt.Color;

/**
 *
 * @author PC
 */
public class pruebas extends javax.swing.JFrame {

    /**
     * Creates new form pruebas
     */
    public pruebas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        backBtn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        asigName = new javax.swing.JLabel();
        actsSection = new javax.swing.JPanel();
        actsTitle = new javax.swing.JLabel();
        loadactsBtn = new javax.swing.JPanel();
        loadIcon = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        acts = new javax.swing.JPanel();
        videosSection = new javax.swing.JPanel();
        videosTitle = new javax.swing.JLabel();
        loadvidBtn = new javax.swing.JPanel();
        loadIcon1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        videos = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Retroceder");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backIcon.png"))); // NOI18N

        javax.swing.GroupLayout backBtnLayout = new javax.swing.GroupLayout(backBtn);
        backBtn.setLayout(backBtnLayout);
        backBtnLayout.setHorizontalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel22)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        backBtnLayout.setVerticalGroup(
            backBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(backBtnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        asigName.setFont(new java.awt.Font("Questrial", 0, 26)); // NOI18N
        asigName.setForeground(new java.awt.Color(221, 224, 229));
        asigName.setText("// Asignatura");
        background.add(asigName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        actsSection.setBackground(new java.awt.Color(255, 255, 255));

        actsTitle.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        actsTitle.setForeground(new java.awt.Color(0, 0, 0));
        actsTitle.setText("Actividades");

        loadactsBtn.setBackground(new java.awt.Color(64, 174, 178));

        loadIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loadIcon.png"))); // NOI18N
        loadIcon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loadIconMouseMoved(evt);
            }
        });
        loadIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loadIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loadactsBtnLayout = new javax.swing.GroupLayout(loadactsBtn);
        loadactsBtn.setLayout(loadactsBtnLayout);
        loadactsBtnLayout.setHorizontalGroup(
            loadactsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        loadactsBtnLayout.setVerticalGroup(
            loadactsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );

        acts.setBackground(new java.awt.Color(153, 153, 153));
        acts.setLayout(new javax.swing.BoxLayout(acts, javax.swing.BoxLayout.X_AXIS));
        jScrollPane2.setViewportView(acts);

        jScrollPane4.setViewportView(jScrollPane2);

        javax.swing.GroupLayout actsSectionLayout = new javax.swing.GroupLayout(actsSection);
        actsSection.setLayout(actsSectionLayout);
        actsSectionLayout.setHorizontalGroup(
            actsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actsSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actsTitle)
                    .addComponent(loadactsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        actsSectionLayout.setVerticalGroup(
            actsSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actsSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadactsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        background.add(actsSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 950, 150));

        videosSection.setBackground(new java.awt.Color(255, 255, 255));

        videosTitle.setFont(new java.awt.Font("Poppins SemiBold", 0, 16)); // NOI18N
        videosTitle.setForeground(new java.awt.Color(0, 0, 0));
        videosTitle.setText("Videos");

        loadvidBtn.setBackground(new java.awt.Color(64, 174, 178));

        loadIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loadIcon.png"))); // NOI18N
        loadIcon1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loadIcon1MouseMoved(evt);
            }
        });
        loadIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loadIcon1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout loadvidBtnLayout = new javax.swing.GroupLayout(loadvidBtn);
        loadvidBtn.setLayout(loadvidBtnLayout);
        loadvidBtnLayout.setHorizontalGroup(
            loadvidBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        loadvidBtnLayout.setVerticalGroup(
            loadvidBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );

        videos.setBackground(new java.awt.Color(153, 153, 153));
        videos.setLayout(new javax.swing.BoxLayout(videos, javax.swing.BoxLayout.X_AXIS));

        jButton1.setText("jButton1");
        videos.add(jButton1);

        jButton2.setText("jButton2");
        videos.add(jButton2);

        jButton3.setText("jButton3");
        videos.add(jButton3);

        jButton4.setText("jButton4");
        videos.add(jButton4);

        jButton5.setText("jButton5");
        videos.add(jButton5);

        jScrollPane1.setViewportView(videos);

        jScrollPane3.setViewportView(jScrollPane1);

        javax.swing.GroupLayout videosSectionLayout = new javax.swing.GroupLayout(videosSection);
        videosSection.setLayout(videosSectionLayout);
        videosSectionLayout.setHorizontalGroup(
            videosSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videosSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(videosSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(videosTitle)
                    .addComponent(loadvidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        videosSectionLayout.setVerticalGroup(
            videosSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videosSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(videosTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadvidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        background.add(videosSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 950, 150));

        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked

    }//GEN-LAST:event_backBtnMouseClicked

    private void loadIconMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadIconMouseMoved
        loadactsBtn.setBackground(new Color(38, 114, 116));
    }//GEN-LAST:event_loadIconMouseMoved

    private void loadIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadIconMouseExited
        loadactsBtn.setBackground(new Color(4, 174, 178));
    }//GEN-LAST:event_loadIconMouseExited

    private void loadIcon1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadIcon1MouseMoved
        loadvidBtn.setBackground(new Color(38, 114, 116));
    }//GEN-LAST:event_loadIcon1MouseMoved

    private void loadIcon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadIcon1MouseExited
        loadvidBtn.setBackground(new Color(4, 174, 178));
    }//GEN-LAST:event_loadIcon1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acts;
    private javax.swing.JPanel actsSection;
    private javax.swing.JLabel actsTitle;
    private javax.swing.JLabel asigName;
    private javax.swing.JPanel backBtn;
    private javax.swing.JPanel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel loadIcon;
    private javax.swing.JLabel loadIcon1;
    private javax.swing.JPanel loadactsBtn;
    private javax.swing.JPanel loadvidBtn;
    private javax.swing.JPanel videos;
    private javax.swing.JPanel videosSection;
    private javax.swing.JLabel videosTitle;
    // End of variables declaration//GEN-END:variables
}
