/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Materia;

import java.awt.Color;

/**
 *
 * @author Mi PC
 */
public class video extends javax.swing.JPanel {

    /**
     * Creates new form video
     */
    public video() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        videoPanel = new javax.swing.JPanel();
        playBtn = new javax.swing.JLabel();
        deletevidBtn = new javax.swing.JPanel();
        deletevidTxt = new javax.swing.JLabel();
        videoName = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        videoPanel.setBackground(new java.awt.Color(15, 96, 99));
        videoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playIcon.png"))); // NOI18N
        videoPanel.add(playBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 180, 60));

        deletevidBtn.setBackground(new java.awt.Color(223, 91, 91));

        deletevidTxt.setFont(new java.awt.Font("Questrial", 0, 17)); // NOI18N
        deletevidTxt.setForeground(new java.awt.Color(255, 255, 255));
        deletevidTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletevidTxt.setText("x");
        deletevidTxt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deletevidTxtMouseMoved(evt);
            }
        });
        deletevidTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletevidTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout deletevidBtnLayout = new javax.swing.GroupLayout(deletevidBtn);
        deletevidBtn.setLayout(deletevidBtnLayout);
        deletevidBtnLayout.setHorizontalGroup(
            deletevidBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(deletevidBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deletevidBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(deletevidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        deletevidBtnLayout.setVerticalGroup(
            deletevidBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
            .addGroup(deletevidBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(deletevidBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(deletevidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        videoPanel.add(deletevidBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        background.add(videoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 100));

        videoName.setFont(new java.awt.Font("Questrial", 0, 17)); // NOI18N
        videoName.setForeground(new java.awt.Color(0, 0, 0));
        videoName.setText("Video");
        background.add(videoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletevidTxtMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletevidTxtMouseMoved
        deletevidBtn.setBackground(new Color(191,40,40));
    }//GEN-LAST:event_deletevidTxtMouseMoved

    private void deletevidTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletevidTxtMouseExited
        deletevidBtn.setBackground(new Color(223,91,91));
    }//GEN-LAST:event_deletevidTxtMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel deletevidBtn;
    private javax.swing.JLabel deletevidTxt;
    private javax.swing.JLabel playBtn;
    private javax.swing.JLabel videoName;
    private javax.swing.JPanel videoPanel;
    // End of variables declaration//GEN-END:variables
}
